### ISSUE TITLE
Ubuntu 16.04 installs python-letsencrypt 0.4.1-1 by default instead of 0.9.3

### ISSUE THREAD

**Issue by GrayPockets** [voxpupuli/puppet-letsencrypt#131]
## Affected Puppet, Ruby, OS and module versions/distributions

- Distribution: Ubuntu
- Module version: 2.4.0

## How to reproduce (e.g Puppet code you use)
Install on Ubuntu-16.04

## What are you seeing
The default letsencrypt package installed is python-letsencrypt 0.4.1-1 https://packages.ubuntu.com/xenial/python-letsencrypt

## What behaviour did you expect instead
It should use version 0.9.3 by default

## Workaround
install_method       => 'vcs',

**Comment by GrayPockets** [comment]
This was caused by #61 , as Ubuntu 16.04 stayed on the previous default version.

**Comment by HT43-bqxFqB** [comment]
This causes a failure to check on every puppet agent run due to the wrong argument for the command.

**Comment by Dan33l** [comment]
Simple using the package provided by the distrib is not a bug.

Does it exists an issue with package of the distrib ?

**Comment by GrayPockets** [comment]
Yes. The older package definitely caused cert renewal issues for me.
The nginx module didn't work at all, as the older package does not contain it.

**Comment by pier4r** [comment]
Example that worked on Ubuntu 16.04 with puppet.

    class { 'letsencrypt':
        configure_epel      => false,
        unsafe_registration => true,
        install_method      => 'vcs',
        version             => 'v0.9.3', #ubuntu 16.04 requirement
        repo                => 'https://github.com/certbot/certbot.git',
    }

**Comment by Dan33l** [comment]
The version provided by ubuntu 16.04 is now python-letsencrypt - 0.7.0

**Comment by pier4r** [comment]
Not really for the LTS version (normally in a ops environment one tends to use LTS versions)

https://packages.ubuntu.com/xenial/allpackages?format=txt.gz
`letsencrypt (0.4.1-1) [universe] Let's Encrypt main client`

**Comment by Dan33l** [comment]
More informations:
https://bugs.launchpad.net/ubuntu/xenial/+source/python-letsencrypt/+bug/1640978
https://bugs.launchpad.net/ubuntu/xenial/+source/python-letsencrypt/+bug/1640978/comments/129

**Comment by Dan33l** [comment]
Since package used by Ubuntu 16.04 is updated, i proceed to close the ticket. Feel free to reopen if you find it should be usefull.
