### ISSUE TITLE
Disabling manage-cron does not remove crontab record

### ISSUE THREAD

**Issue by Kentzo** [voxpupuli/puppet-letsencrypt#139]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.12
- Module version: 2.4.0

## How to reproduce (e.g Puppet code you use)
Set letsencrypt::certonly::manage-cron to true, sync, set to false, sync

## What are you seeing
crontab record and script are still present

## What behaviour did you expect instead
at least the crontab record should be removed

**Comment by bastelfreak** [comment]
Hey @Kentzo, thanks for reporting this bug. Are you able to provide a PR for this?
