### ISSUE TITLE
wrong initialize script 

### ISSUE THREAD

**Issue by Dan33l** [voxpupuli/puppet-letsencrypt#154]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: any
- Ruby: any
- Distribution: any
- Module version: 2.5.0

## What are you seeing
When using `install_method => vcs`, the module use `letsencrypt-auto`
```puppet
  $command_init = $install_method ? {
     'package' => $package_command,
     'vcs'     => "${path}/letsencrypt-auto",
   }
```

## What behaviour did you expect instead

Until May 2016, Certbot was named `letsencrypt` or `letsencrypt-auto`. Now, the expected used script is `certbot-auto`. 

For the moment  `letsencrypt-auto` and  `certbot-auto` are same, and so the module works as expected.

**Comment by kenyon** [comment]
Closing because there is no VCS install method anymore, it was removed in commit ee77abc.
