### ISSUE TITLE
Option to clean up cronjobs for removed domains

### ISSUE THREAD

**Issue by cFire** [voxpupuli/puppet-letsencrypt#175]
There is currently no way for the module to clean up cronjobs when a domain is no longer in use.

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: any
- Ruby: any
- Distribution: any
- Module version: 3.0.1-rc1

## How to reproduce (e.g Puppet code you use)
- Provision some certificate using `letsencrypt::certonly` with the `ensure_cron` option enabled.
- This domain stops being available for any reason (domain expired, DNS changed etc.)
- Try to de-provision cronjobs for renewing the certificate by setting `ensure_cron` to disabled.
- Module still tries (and of course fails) to get a certificate for the domain.
- Removing cronjobs fails because of failed dependencies.

## Output log
```
Error: 'certbot --text --agree-tos --non-interactive certonly --rsa-key-size 4096 -a apache --cert-name LE_redacted.com -d redacted.com' returned 1 instead of one of [0]
Error: /Stage[main]/Profile::Lydia/Profile::Lydia::User[redacted]/Site_apache::Vhost::User[redacted.com]/Letsencrypt::Certonly[LE_redacted.com]/Exec[letsencrypt certonly LE_redacted.com]/returns: change from 'notrun' to ['0'] failed: 'certbot --text --agree-tos --non-interactive certonly --rsa-key-size 4096 -a apache --cert-name LE_redacted.com -d redacted.com' returned 1 instead of one of [0]
```

## Any additional information you'd like to impart
This is a feature request, not a bug as the module is intended to function as it is doing, but there currently seems to be no options to deal with this sort of cleanup.

**Comment by Dan33l** [comment]
It looks we didn't release it but what do you think about `ensure_cron` attribute ?
https://github.com/voxpupuli/puppet-letsencrypt/blob/master/manifests/certonly.pp#L51

**Comment by cFire** [comment]
That's only half the puzzle. I'm using the pre-release version from git but it will still try to `exec { "letsencrypt certonly ${title}":`, which is no good if the domain is gone.

Perhaps we can add a normal `ensure` attribute which just takes 'absent/present'? That way we have a neat way both to clean up old certs, and to clean up cron jobs and scripts if enabled.

**Comment by Dan33l** [comment]
You are right.

Can you propose a PR for this enhancement ?

**Comment by cFire** [comment]
Sure. I'll try to fit it in somewhere this week. But I think the older `manage_cron` attribute may then be more aptly named again rather than the `ensure_cron` from 3.0.1-rc1. And as an added bonus if we change it back, it would still be backward compatible with puppet code using the 3.0.0 release.

**Comment by Dan33l** [comment]
Yes, it looks possible.

**Comment by cFire** [comment]
Created https://github.com/voxpupuli/puppet-letsencrypt/pull/177 to see if you agree on the general changes made. Still needs testing and need to think if there's a nicer way to do the `exec{}` and `file{}` rather than wrapping them in an if/else.

**Comment by Dan33l** [comment]
Fixer by PR #177
