### ISSUE TITLE
python2-certbot-dns-rfc2136 doesn't exist in debian buster

### ISSUE THREAD

**Issue by davidsev** [voxpupuli/puppet-letsencrypt#191]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.7.0
- Ruby: 2.5.5p157
- Distribution: Debian 10 (Buster)
- Module version: 4.0.0

## How to reproduce (e.g Puppet code you use)

```puppet
letsencrypt::certonly { 'foo':
    domains       => ['example.com'],
    plugin        => 'dns-rfc2136',
}
```

## What are you seeing

    E: Unable to locate package python2-certbot-dns-rfc2136

## Any additional information you'd like to impart

I set `letsencrypt::plugin::dns_rfc2136::manage_package: false` and manually installed `python3-certbot-dns-rfc2136` and it works fine.

**Comment by ekohl** [comment]
#193 fixes this.
