### ISSUE TITLE
replace server urls with v2 urls

### ISSUE THREAD

**Issue by hboetes** [voxpupuli/puppet-letsencrypt#196]
Please replace the server URLs with:

https://acme-v02.api.letsencrypt.org/directory
And 
https://acme-staging-v02.api.letsencrypt.org/directory

See also:

https://community.letsencrypt.org/t/staging-endpoint-for-acme-v2/49605
https://community.letsencrypt.org/t/acme-v2-production-environment-wildcards/55578

**Comment by Dan33l** [comment]
Hi @hboetes 

Why modify the [default value of $config](https://github.com/voxpupuli/puppet-letsencrypt/blob/master/manifests/params.pp#L15) does not meet your needs ?

**Comment by hboetes** [comment]
The code should use sane defaults and in this case use the working server URL, not the outdated one. Your proposal would force all users of the module to fix that problem for themselves whereas the maintainer can fix the problem for everyone.

**Comment by ekohl** [comment]
With reading those sources I agree we should be defaulting to v2. I also wonder why we even set a default rather than relying on the hardcoded defaults. Probably because we use `ini_setting` and don't purge.

**Comment by hboetes** [comment]
@ekohl I can imagine setting staging as the default, since I’ve never managed to get a cert in one go and use the production one as the non-default, with a switch like: `production => true`
I also see no reason for using anything else but hard coded URLs.
