### ISSUE TITLE
letsencrypt package requirements

### ISSUE THREAD

**Issue by advorkin** [voxpupuli/puppet-letsencrypt#215]
Hello.

We are running a custom RedHat based distribution and do not have letsencrypt package readily available.  We also do not want to use EPEL repo.

I am wondering if pip module letsencrypt can be used?  If so, whenever I have tried to add a package with provider 'pip', I get an error of a duplicate declaration.

    package {
      'letsencrypt':
        ensure   => present,
        require  => Package['python3-pip'],
        provider => pip3;
    }

> Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Package[letsencrypt] is already declared at (file: /etc/puppetlabs/code/environments/puppet6/site-modules/cspuppetmaster/manifests/init.pp, line: 13); cannot redeclare (file: /etc/puppetlabs/code/environments/puppet6/modules/letsencrypt/manifests/install.pp, line: 39) (file: /etc/puppetlabs/code/environments/puppet6/modules/letsencrypt/manifests/install.pp, line: 39, column: 5) 

Is there a way around it?

Thank you and happy new year!

Asya

**Comment by ekohl** [comment]
You should probably use [manage_install](https://github.com/voxpupuli/puppet-letsencrypt/blob/master/REFERENCE.md#manage_install. [install_method](https://github.com/voxpupuli/puppet-letsencrypt/blob/master/REFERENCE.md#install_method) can also be used to install from VCS. It does pull in a virtualenv as well, but I think that might actually be a nice thing to isolate the system.

**Comment by advorkin** [comment]
Thank you for a quick response.  Just so that I understand, install_method will install it's own virtual environment?  Do I still need to install letsencrypt with pip or it'll take care of it?

Thank you!

**Comment by ekohl** [comment]
That should take care of it all.

**Comment by advorkin** [comment]
Thank you.  Now It's looking for an epel module, even though I have specified not to.

    class { 'letsencrypt':
      config         =>   {
        configure_epel => false,
        install_method => 'vcs',
        server         => 'https://acme-staging.api.letsencrypt.org/directory',
      }

Does it need epel in order to install using vcs?

Again, thank you for helping me during a holiday week.

**Comment by advorkin** [comment]
Sorry, I forgot to include an error message.  Thank you.

> Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Could not find class ::epel for  (file: /etc/puppetlabs/code/environments/puppet6/modules/letsencrypt/manifests/install.pp, line: 45, column: 7)

**Comment by advorkin** [comment]
For testing purposes, I did add epel to Puppetfile and ran puppet --noop.

Notice: /Stage[main]/Letsencrypt::Install/Package[letsencrypt]/ensure: current_value 'purged', should be 'present' (noop)

Does it mean it will attempt to install letsencrypt as a package from epel?

Also, do I need to specify config_dir?  With a virtual environment, I assume everything will be isolated to a specific directory (not /etc/letsencrypt).

    class { 'letsencrypt::plugin::dns_rfc2136':
      config_dir => '/etc/letsencrypt',

Without it, I was getting an error:

> Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Unknown variable: 'letsencrypt::config_dir'.

I'm sorry for so many questions and thank you for your help.

**Comment by ekohl** [comment]
I personally don't use the VCS method so I can't really say. If you don't want to pull in EPEL, I'd prefer to still use packages. There's `configure_epel`. This is also how Fedora is supported: the packages are just available.

**Comment by advorkin** [comment]
As I have mentioned, we have our own RedHat based OS, thus build our own packages.  Building our own letsencrypt is a big project (has multiple requirements), so using letsencrypt python module sounds like a good alternative...  Thank you.

**Comment by advorkin** [comment]
Hello.  I was able to create a local letsencrypt package and changed the code to the following:

```
    class { 'letsencrypt':
      config         =>   {
        email          => 'blah@blah.com,
        configure_epel => false,
        server         => 'https://acme-staging.api.letsencrypt.org/directory',
      }
    }
```
Unfortunately, I am still getting an error message 

> Could not find class ::epel

I am wondering if I am missing something and would appreciate your advice.  Thank you.

**Comment by advorkin** [comment]
I think it was my syntax mistake.  I will close the ticket for now.  Thank you for all your help.
