### ISSUE TITLE
typo in example

### ISSUE THREAD

**Issue by milesstoetzner** [voxpupuli/puppet-letsencrypt#227]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: any
- Ruby: any
- Distribution: any
- Module version: any

## What are you seeing

There is a typo in the "Renewing certificates" example of the [README.md](https://github.com/voxpupuli/puppet-letsencrypt/blob/1ba9341f5be6008f68c8d8c3b8a99eedbdef0838/README.md#renewing-certificates
). 

```
  renew_cron_ensure: 'present',
````

## What behaviour did you expect instead

It should be 
```
  renew_cron_ensure => 'present',
````

**Comment by ekohl** [comment]
Would you mind sending a PR so you're properly attributed in the changelog? Github provides an in-browser editor that makes this easy.

**Comment by milesstoetzner** [comment]
I created a PR; see https://github.com/voxpupuli/puppet-letsencrypt/pull/228
