### ISSUE TITLE
Logrotate for the letsencrypt logs

### ISSUE THREAD

**Issue by ashish1099** [voxpupuli/puppet-letsencrypt#237]
just looked at one of my system that the letsencrypt logs are lying there around 650 files and it should be logrotate.

let me know if that would be a nice addition to the module, I can raise a PR for this one.

**Comment by kenyon** [comment]
The Let's Encrypt `certbot` package takes care of this: https://eff-certbot.readthedocs.io/en/stable/using.html#log-rotation
