### ISSUE TITLE
certbot-auto no longer works on any OS

### ISSUE THREAD

**Issue by carljohnstone** [voxpupuli/puppet-letsencrypt#240]
See https://community.letsencrypt.org/t/certbot-auto-no-longer-works-on-debian-based-systems/139702/6

certbot-auto is no longer being supported, so therefore refuses to update/install certbot. This removal has been rolled out in monthly stages over the last few months. Their recommendation is to now use `snap` as the installation method.

When vcs is used as the install method, the certbot-auto script is called which now fails. As all the per-OS CI tests use the vcs installation method, this has had the effect of breaking CI for any change.

**Comment by carljohnstone** [comment]
#235 #238 #239 are all PRs failing CI due to this issue

**Comment by ekohl** [comment]
We ended up removing VCS support in https://github.com/voxpupuli/puppet-letsencrypt/commit/ee77abc6ea9ca114f8fec382522abfe56571daef and always use packages.
