### ISSUE TITLE
Raise compatible puppet version from <7.0 to <8.0

### ISSUE THREAD

**Issue by Fightbackman** [voxpupuli/puppet-letsencrypt#245]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.X
- Ruby: -
- Distribution: any
- Module version: 6.0.0

## How to reproduce (e.g Puppet code you use)
The module list only puppet versions <7.0 as compatible

## What are you seeing
A warning by puppet-lint and problem resolvinh dependencies for the puppet7 environment.
The module itself seems to work without problems in my setup on debian buster and stretch systems.

## What behaviour did you expect instead
Puppet module compatible for puppet version <8.0

## Output log
- 
## Any additional information you'd like to impart
If you need further information or help in making these changes feel free to reach out and I'll try to help.

**Comment by kenyon** [comment]
This will be fixed in #235, which we could use help with.

**Comment by ekohl** [comment]
Resolved in https://github.com/voxpupuli/puppet-letsencrypt/commit/4fad787be92524ef6eb1dfb6515172a6b86084c9#diff-12e598daecade60b04e493f45c134fec9287ac7471114d95d1995b4fb651a6c8
