### ISSUE TITLE
Could not find class ::epel when declaring Letsencrypt class

### ISSUE THREAD

**Issue by Surowa** [voxpupuli/puppet-letsencrypt#290]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.22
- Ruby:
- Distribution: CentOS 7 Core
- Module version:

## How to reproduce (e.g Puppet code you use)

  class { 'letsencrypt':
    config =>  {
      email  => 'email_address@domain.com',
      server => "https://${server}/acme/directory",
    }
  }

## What are you seeing
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Could not find class ::epel for $node (file: /srv/puppet/environments/$envname/modules/letsencrypt/manifests/install.pp, line: 18, column: 5) (file: /srv/puppet/environments/$envname/modules/$modulename/manifests/init.pp, line: 46) on node $node

## What behaviour did you expect instead
Being able to import an ::epel subclass or just being able to run the encrypt.

**Comment by ekohl** [comment]
This is a documented soft dependency: https://github.com/voxpupuli/puppet-letsencrypt#dependencies describes that you are responsible for having the EPEL module present in your environment. Perhaps it can be more explicit in saying that it is a soft dependency and a PR for that is welcome, but this is the desired workflow.
