### ISSUE TITLE
New release please?

### ISSUE THREAD

**Issue by adamretter** [voxpupuli/puppet-letsencrypt#293]
Would it be possible for you to publish a new release of this Puppet Module please?
We are very keen to use the new Cloudflare support (https://github.com/voxpupuli/puppet-letsencrypt/pull/279) which isn't in the latest release (8.0.2).

**Comment by y509488** [comment]
Please publish new release - I really need the manual plugin.

**Comment by ekohl** [comment]
You can help by doing the preparation steps. https://voxpupuli.org/docs/releasing_version/ documents those. If you run that up to the changelog generation and then submit that as a PR it'll help.

We're always looking for new people to help maintain modules

**Comment by apeeters** [comment]
Seems to be fixed in [v9.0.0](https://github.com/voxpupuli/puppet-letsencrypt/blob/master/CHANGELOG.md#user-content-v900-2022-11-21).
