### ISSUE TITLE
Documentation/examples for certonly `suppress_cron_output` not updated after removal of parameter

### ISSUE THREAD

**Issue by cFire** [voxpupuli/puppet-letsencrypt#302]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.20.0
- Ruby: 2.7.6p219
- Distribution: Debian 11
- Module version: 9.0.0

## How to reproduce (e.g Puppet code you use)
```puppet
letsencrypt::certonly { "LE_${user}_${domain}":
  ensure              => $ensure_default,
  manage_cron         => true,
  domains             => $domains,
  plugin              => 'apache',
  supress_cron_output => true,
}
```
## What are you seeing
The above code is still correct according to documentation/examples but of course now produces an error when applying:
`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Letsencrypt::Certonly[LE_redacted_redacted]: has no parameter named 'suppress_cron_output' (file: /etc/puppetlabs/code/environments/production/modules/site_apache/manifests/vhost/user.pp, line: 74) on node host.example.com`.

It seems the `suppress_cron_output` parameter was removed in f6a6a4ee812f0d6282912f609ab4cec9a03dc395 in favor of the `cron_output` parameter which has the `suppress` option to replace the functionality. Documentation and example code was not updated to reflect these changes.

**Comment by treydock** [comment]
@cFire The fix is in #303.  Not sure how that got missed during the release process.  That's the only place I could find a reference to the old parameter.
