### ISSUE TITLE
No letsencrypt package for centos 6?

### ISSUE THREAD

**Issue by tmountjr** [voxpupuli/puppet-letsencrypt#31]
I installed this module and ran it against a CentOS 6.7 system. I made sure to set the `configure_epel` option to `true` but I received the following error when applying the manifest:

```
Error: Execution of '/usr/bin/yum -d 0 -e 0 -y list letsencrypt' returned 1: Error: No matching Packages to list
Error: /Stage[main]/Letsencrypt/Letsencrypt::Install/Package[letsencrypt]/ensure: change from absent to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y list letsencrypt' returned 1: Error: No matching Packages to list
Notice: /Stage[main]/Letsencrypt/Exec[initialize letsencrypt]: Dependency Package[letsencrypt] has failures: true
```

(I should note that I had `include epel` in my primary manifest already, so EPEL should have already been configured.)

Looking through the EPEL package list I don't see letsencrypt listed anywhere (I assume [here](https://dl.fedoraproject.org/pub/epel/6/x86_64/repoview/letter_l.group.html) is the right place to look). I'm wondering if I'm missing something? I suppose it's possible that support for an RPM for letsencrypt got dropped from EPEL somewhere along the line. If that's true and there is no current RPM for letsencrypt, should the documentation be changed to reflect that?

**Comment by danzilio** [comment]
Hi @tmountjr! I'll look into whether this is a sane default going forward, but to get you up and running you should be able to set the `install_method` param to `vcs`

**Comment by tmountjr** [comment]
Thanks, I just saw that option in the source code this morning; haven't had a chance to play with it yet.

**Comment by domcleal** [comment]
2a01fb5 also fixes this by changing `install_method` to `vcs` on EL6 and older.
