### ISSUE TITLE
Testing: Change the server or use --staging?

### ISSUE THREAD

**Issue by fvanboven** [voxpupuli/puppet-letsencrypt#43]
The readme states that the server configuration should be changed if you want to use the staging environment. But CertBot itself can handle this using the "-- staging" argument. 

Isn't it perhaps a nice feature to make this a solid part of the module? To create a consistent way of testing and keeping the logic of the e.g. the staging server hostname out of the implementation. 

Something like:

``` puppet
certbot::certonly { 'foo':
  domains => ['foo.example.com', 'bar.example.com'],
  staging => true,
}
```

Or make it a machine-wide config:

``` puppet
class { ::certbot:
  staging => true,
}
```

Any thoughts on this?

**Comment by danzilio** [comment]
Hmm...this is an interesting idea. I wonder what this would mean for people using their own internal ACME server.

**Comment by cjeanneret** [comment]
@danzilio you might want to provide both way in your module: either use "default LE remotes" and using the --staging switch, or allow user to set his own remote - in that case, "staging" should not be passed (and ignored if passed).

**Comment by ekohl** [comment]
Per our README: the answer is to change the server.
