### ISSUE TITLE
Add dependencies as a parameter

### ISSUE THREAD

**Issue by c33s** [voxpupuli/puppet-letsencrypt#52]
kind of related to: #41 

hardcoded parameters are not that good, having `$package_name` and `$dependency` as a parameter for `letsencrypt::install` would be awesome.

https://github.com/danzilio/puppet-letsencrypt/blob/v1.0.0/manifests/install.pp#L56
https://github.com/danzilio/puppet-letsencrypt/blob/v1.0.0/manifests/install.pp#L62
https://github.com/danzilio/puppet-letsencrypt/blob/v1.0.0/manifests/install.pp#L44

```
class letsencrypt::install (
  $package_name        = $letsencrypt::package_name, # 'letsencrypt' or 'certbot'
  $dependencies        = $letsencrypt::dependencies, # ['python', 'git']
  $manage_install      = $letsencrypt::manage_install,
  $manage_dependencies = $letsencrypt::manage_dependencies,
  $configure_epel      = $letsencrypt::configure_epel,
  $install_method      = $letsencrypt::install_method,
  $package_ensure      = $letsencrypt::package_ensure,
  $path                = $letsencrypt::path,
  $repo                = $letsencrypt::repo,
  $version             = $letsencrypt::version,
)
```

```
  if $install_method == 'vcs' {
    if $manage_dependencies {
      ensure_packages($dependencies)
      Package[$dependencies] -> Vcsrepo[$path]
}
```

```
    package { $package_name:
      ensure => $package_ensure,
}
```

because for example `ensure_packages($dependencies)` causes an error, if a manifest already includes `package { 'git': }` or `package { 'python': }` and not `ensure_packages(['git'])` which sadly is quite common.

**Comment by danzilio** [comment]
`$package_name` is already a parameter on `letsencrypt::install` (though, a version with this param has not been pushed yet) and we have a feature flag to disable managing the dependencies in this module if there's a conflict via the `$manage_dependencies` flag. But, I see your point and I would accept a PR that added a `$dependencies` param to this class.

**Comment by c33s** [comment]
i am a little bit confused, i have seen, that there is a parameter for `$package_name` but it isn't used but it has been used before commit https://github.com/danzilio/puppet-letsencrypt/commit/aa9f9ab17cd00cdfaf903e5ead37fcd512ba6955

i will happily provide a PR for `$dependencies`, should i wait for your push of the revert to `$package_name` or should i also include that in my PR?

**Comment by ekohl** [comment]
We have a parameter for the package name. The workaround for dependencies is to pass in `manage_dependencies => false` and manage them yourself so I'm going to close this issue. A patch to add the dependencies would be accepted though.
