### ISSUE TITLE
Cronjob needs the options --text --non-interactive

### ISSUE THREAD

**Issue by westbywest** [voxpupuli/puppet-letsencrypt#55]
The cronjob deployed by this module needs the command line options '--text --non-interactive' to avoid PythonDialogBug occurring under certain platforms.  I get this under CentOS 7.  The issue filed below with certbot reports it occurring under Ubuntu 14.04.
https://github.com/certbot/certbot/issues/1154

**Comment by jethrocarr** [comment]
PR #58 should address this.
