### ISSUE TITLE
Add support for certbot hooks

### ISSUE THREAD

**Issue by bakerkj** [voxpupuli/puppet-letsencrypt#56]
--pre-hook PRE_HOOK   Command to be run in a shell before obtaining any
                        certificates. Intended primarily for renewal, where it
                        can be used to temporarily shut down a webserver that
                        might conflict with the standalone plugin. This will
                        only be called if a certificate is actually to be
                        obtained/renewed. (default: None)

  --post-hook POST_HOOK
                        Command to be run in a shell after attempting to
                        obtain/renew certificates. Can be used to deploy
                        renewed certificates, or to restart any servers that
                        were stopped by --pre-hook. This is only run if an
                        attempt was made to obtain/renew a certificate.
                        (default: None)

  --renew-hook RENEW_HOOK
                        Command to be run in a shell once for each
                        successfully renewed certificate.For this command, the
                        shell variable $RENEWED_LINEAGE will point to
                        theconfig live subdirectory containing the new certs
                        and keys; the shell variable $RENEWED_DOMAINS will
                        contain a space-delimited list of renewed cert domains
                        (default: None)

**Comment by vide** [comment]
In particualr `--renew-hook` would be a far better implementation for what `cron_success_command` is trying to achieve, because the cron is basically always returning true at every execution and it's completely useless.

**Comment by xdexter** [comment]
+1

**Comment by TNAJanssen** [comment]
--renew-hook is already gone and replaced by --deploy-hook

https://blog.wizardsoftheweb.pro/certbot-hook-api/

**Comment by Rathios** [comment]
I'm interested in working on this as I'd rather use `certbot renew` w/ hooks than the current solution. I'll see what I can come up with ...

**Comment by bastelfreak** [comment]
Hey @Rathios, feel free to provide a PR with anything you can come up with. We're happy to assist you. Let us know if you need any help.
