### ISSUE TITLE
Using a space in the letsencrypt::certonly title creates a cron script that will never run.

### ISSUE THREAD

**Issue by andrewwippler** [voxpupuli/puppet-letsencrypt#91]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.0
- Ruby: ruby 2.1.9p490 
- Distribution: Ubuntu 16.04.2 LTS (Xenial Xerus)
- Module version: commit e72470c5aa7db82ce0b59704b85f6ba3cd9a8287 (May 9th - latest commit)

## How to reproduce (e.g Puppet code you use)

```puppet
    letsencrypt::certonly { "LE ${server}":
      domains                           => [$server,],
      manage_cron                   => true,
      plugin                               => 'webroot',
      webroot_paths                 => [$webroot],
      cron_success_command => '/bin/systemctl reload nginx.service',
    }
```

## What are you seeing
Note with the space in the name above, the module improperly creates a file with a space in the name. When running the command from cron, it would fail due to the space not being escaped.

## What behaviour did you expect instead
The cron script substituting a character for space.

## Any additional information you'd like to impart
Obviously this is an edge case and I fixed my issue by substituting the space with a `-`.

**Comment by juniorsysadmin** [comment]
Closed by #113
