### ISSUE TITLE
Update to support puppetlabs/inifile 2

### ISSUE THREAD

**Issue by cristianbalan-mf** [voxpupuli/puppet-letsencrypt#97]
Could you please update to support puppetlabs/inifile 2?

**Comment by bastelfreak** [comment]
Hi @cristianbalan, thanks for the request. Are you able to provide a patch for this?

**Comment by cristianbalan** [comment]
I can do a local test and eventually push an update to the metadata.json if everything goes fine. But if is negative, then I'm not sure I'll have the time and expertise to go further.

**Comment by ekohl** [comment]
Done in 2587248ecb787f3c0411f403e812f6832272a688
