### ISSUE TITLE
Update to support puppetlabs/vcsrepo 2

### ISSUE THREAD

**Issue by cristianbalan-mf** [voxpupuli/puppet-letsencrypt#98]
Could you please update to support puppetlabs/vcsrepo 2?

**Comment by bastelfreak** [comment]
Hi @cristianbalan, thanks for this issue. Are you able to provide a patch for this?

**Comment by cristianbalan** [comment]
I can do a local test @bastelfreak and eventually push an update to the metadata.json if everything goes fine. But if is negative, then I'm not sure I'll have the time and expertise to go further.

**Comment by juniorsysadmin** [comment]
puppetlabs/vcsrepo should probably be a soft dependency, not a hard one. See https://docs.puppet.com/puppet/latest/style_guide.html#dependencies

**Comment by ekohl** [comment]
Done in 10463a244dff511c5e75af974a915965bdd89550
